# Generated by Django 6.0 on 2026-01-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('developer', 'Developer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dev_specialization',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('security', 'Security')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=10),
        ),
    ]
