# Generated by Django 6.0 on 2026-01-22 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_admin_type_user_dev_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('MANAGER', 'MANAGER'), ('DEVELOPER', 'DEVELOPER')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dev_specialization',
            field=models.CharField(blank=True, choices=[('FRONTEND', 'FRONTEND'), ('BACKEND', 'BACKEND'), ('SECURITY', 'SECURITY')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('TEACHER', 'TEACHER'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=10),
        ),
    ]
