# Generated by Django 6.0 on 2026-01-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_uuid_alter_user_admin_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('Manager', 'MANAGER'), ('Developer', 'DEVELOPER')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dev_specialization',
            field=models.CharField(blank=True, choices=[('Frontend', 'FRONTEND'), ('Backend', 'BACKEND'), ('Security', 'SECURITY')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('Teacher', 'TEACHER'), ('Student', 'STUDENT')], default='Student', max_length=10),
        ),
    ]
