# Generated by Django 5.2.10 on 2026-05-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_admin_type_alter_user_dev_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('DEVELOPER', 'Developer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dev_specialization',
            field=models.CharField(blank=True, choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('SECURITY', 'Security')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PREMIUM_STUDENT', 'Premium Student'), ('PREMIUM_TEACHER', 'Premium Teacher')], default='STUDENT', max_length=30),
        ),
    ]
