# Generated by Django 5.2.10 on 2026-05-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_admin_type_alter_user_dev_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PREMIUM_STUDENT', 'Premium Student'), ('PREMIUM_TEACHER', 'Premium Teacher'), ('SYS', 'Sys')], default='STUDENT', max_length=30),
        ),
    ]
