# Generated by Django 5.2.10 on 2026-07-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code_used',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
