# Generated by Django 5.2.10 on 2026-05-06 03:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e411324c-b1d6-46ba-9eb4-f49e41f791b2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
