# Generated by Django 5.2.10 on 2026-05-06 03:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de6730dc-b23d-4cfb-babe-3729d7258d11'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2eae6e5-c8fe-47b7-91cb-b5d9e1fc8413'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a1b6627a-6c3a-4046-b951-be1532eafa78'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
