# Generated by Django 5.2.10 on 2026-05-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_transaction_id_alter_wallet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payout_info',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
