# Generated by Django 5.2.10 on 2026-07-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction_payout_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('view_any_transaction', 'Can view any wallet transaction')], 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'permissions': [('view_any_wallet', 'Can view any wallet'), ('reconcile_wallet', 'Can reconcile wallet balances')]},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'permissions': [('view_any_withdrawal', 'Can view any withdrawal'), ('approve_withdrawal', 'Can approve or reject withdrawals'), ('process_withdrawal', 'Can process approved withdrawals')], 'verbose_name_plural': 'Withdrawals'},
        ),
    ]
