# Generated by Django 6.0 on 2025-12-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_ADMIN', 'Create Admin'), ('DELETE_USER', 'Delete User')], max_length=50),
        ),
    ]
