# Generated by Django 6.0 on 2025-12-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_ADMIN', 'Create Admin'), ('DELETE_USER', 'Delete User'), ('FAILED_ADMIN_LOGIN', 'Failed Admin Login'), ('SUCCESS_ADMIN_LOGIN', 'Success Admin Login')], max_length=50),
        ),
    ]
