# Generated by Django 5.2.10 on 2026-07-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpackage',
            name='withdrawal_threshold',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Balance at which premium expires and earnings are frozen', max_digits=12),
            preserve_default=False,
        ),
    ]
