# Generated by Django 5.2.10 on 2026-07-23 01:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_premiumpackage_withdrawal_threshold'),
        ('wallet', '0005_transaction_payout_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPremiumSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Set when duration_days lapses or threshold is hit', null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='premium.premiumpackage')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='premium_subscription', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Premium Subscription',
                'verbose_name_plural': 'Premium Subscriptions',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
