# Generated by Django 5.2.10 on 2026-07-18 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0005_transaction_payout_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_referral', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Referral',
                'verbose_name_plural': 'Pending Referrals',
            },
        ),
        migrations.CreateModel(
            name='ReferralNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('left_child', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_left_child', to='referral.referralnode')),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='referral.referralnode')),
                ('right_child', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_right_child', to='referral.referralnode')),
                ('root_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tree_members', to='referral.referralnode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral_node', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Node',
                'verbose_name_plural': 'Referral Nodes',
            },
        ),
        migrations.CreateModel(
            name='PlacementQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], default='LEFT', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_available_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queued_as_next', to='referral.referralnode')),
                ('root_node', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='placement_queue', to='referral.referralnode')),
            ],
            options={
                'verbose_name': 'Placement Queue',
                'verbose_name_plural': 'Placement Queues',
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_event_id', models.CharField(max_length=100)),
                ('percentage_applied', models.PositiveIntegerField()),
                ('depth_difference', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_rewards_received', to=settings.AUTH_USER_MODEL)),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_rewards_triggered', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_reward', to='wallet.transaction')),
            ],
            options={
                'verbose_name': 'Referral Reward',
                'verbose_name_plural': 'Referral Rewards',
                'constraints': [models.UniqueConstraint(fields=('source_user', 'beneficiary', 'purchase_event_id'), name='unique_reward_per_purchase_per_ancestor')],
            },
        ),
    ]
